### ISSUE TITLE
Installing gustoL09P  fails

### ISSUE THREAD

**Issue by rfshipman** [craigkulesa/gusto-datasystem#10]
On level09 branch:
pip install -e gustoL09P --use-feature=in-tree-build

gives the following error:
option --use-feature: invalid choice: 'in-tree-build' (choose from 'fast-deps', 'truststore', 'no-binary-enable-wheel-cache')

in-tree-build is not one of the options.

**Comment by rfshipman** [comment]
I also try to install gustoL09P without the --use-feature= 
I get the following errors:
### In the level0.9 directory 
pip install -e gustoL09P 
ERROR: gustoL09P is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

### In level0.9/src directory
pip install -e gustoL09P 
Obtaining file:///data/scratch/GUSTO/gusto-datasystem/level0.9/src/gustoL09P
ERROR: file:///data/scratch/GUSTO/gusto-datasystem/level0.9/src/gustoL09P does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

### In level0.9 directory which has a pyproject.toml
pip install -e src/gustoL09P 
Obtaining file:///data/scratch/GUSTO/gusto-datasystem/level0.9/src/gustoL09P
ERROR: file:///data/scratch/GUSTO/gusto-datasystem/level0.9/src/gustoL09P does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by cmartin-kavlifoundation** [comment]
As described on the call:
cd gusto-datasystem/level0.9
pip install -e .

works for me.  If this works for you too, we can probably close this issue.

**Comment by vtcloud** [comment]
@cmartin, yes, this is the way to install the package. I will edit the README file appropriately. Then we can close the issue.

**Comment by cmartin** [comment]
Got the wrong '@'. cmartin-kavlifoundation was probably not notified...

**Comment by vtcloud** [comment]
@cmartin-kavlifoundation, yes, this is the way to install the package. I edited the README file appropriately. We can close the issue.

**Comment by vtcloud** [comment]
@cmartin, Thank you. Sorry about that.

**Comment by rfshipman** [comment]
I can install and run the L09 pipeline.

**Comment by rfshipman** [comment]
GL
