### ISSUE TITLE
Level 0.9 doesn't retain Row_flags

### ISSUE THREAD

**Issue by abegyoung** [craigkulesa/gusto-datasystem#20]
gusto-datasystem/level0.9/src/gustoL09P/GL09Pipeline.py
line 468 fills the newly created fits file with np.zeros.

Further, rows with non zero row_flags are removed from the Level0.9 output

Better to retain the data on line 392 by removing ROW_FLAG==0 from the np.argwhere()
and load the level0.8 row flags with ROW_FLAG = data['ROW_FLAG][osel]

col12 can then be filled with ROW_FLAG and no information is lost from level0.8 to level0.9

**Comment by vtcloud** [comment]
The latest version as off 11/20/2024 should retain the flag.

**Comment by rfshipman** [comment]
which commit tag is that?  That would be useful to keep track of issues and to check when they can be closed.

**Comment by abegyoung** [comment]
commit 0x065655 retains the row flag
