### ISSUE TITLE
New HISTORY entry is added even if the task has been executed

### ISSUE THREAD

**Issue by rfshipman** [craigkulesa/gusto-datasystem#21]
If I run  either the set_ban_chflag or set_noisy_rowflag scripts on data where they have been run before, they scripts still leave a a new HISTORY comment.   I would expect the scripts to skip over the file not to touch it.

**Comment by abegyoung** [comment]
fixed for both scripts in commit 0x28940f3
changed "exit" to "return" if flagging was in history

use --force if you want to skip the check of history and do anyway
